languageCode: "en-gb"
uglyURLs: false
title: "COAR Notify Documentation"
theme: "coar_notify"
enableRobotsTXT: true
#disableKinds: ["RSS","taxonomy","taxonomyTerm"]
disableKinds: [ "RSS" ]
metaDataFormat: "yaml"
enableGitInfo: false
blackfriday:
  smartypants: false
  smartDashes: false
  extensionsmask: [ "autolink" ] #disables these extensions
disablePathToLower: true
taxonomies:
  tag: "tags"
  status: "status"
params:
  namespaces:
    sorg:
      name: "schema.org"
      uri: "http://schema.org/"
    ldp:
      name: "W3C Linked Data Platform (LDP) Vocabulary"
      uri: "http://www.w3.org/ns/ldp#"
    nat:
      name: "Notify Activity Types"
      uri: "http://purl.org/coar/notify_activity_type/"
    ietf:
      name: "IETF Link Relations"
      uri: "http://www.iana.org/assignments/relation/"
    cito:
      name: "CiTO, the Citation Typing Ontology"
      uri: "http://purl.org/spar/cito/"
    nrr:
      name: "Notify Resource Relations"
      uri: "http://purl.org/coar/notify_resource_relations/"
    rt:
      name: "COAR Resource Types"
      uri: "http://purl.org/coar/resource_type"
  #  patterns:
  #    offer:
  #      id: "urn:uuid:0370c0fb-bb78-4a9b-87f5-bed307a509dd"
  #      type: "Offer"
  actors:
    generic_actor:
      "@id": "https://orcid.org/0000-0002-1825-0097"
      name: "Josiah Carberry"
      "@type": "Person"
      "ldp:inbox": "https://josiahcarberry.com/ldn/inbox"
    author:
      "@id": "https://orcid.org/0000-0002-1825-0097"
      name: "Josiah Carberry"
      "@type": "Person"
      "ldp:inbox": "https://josiahcarberry.com/ldn/inbox"
    reviewer:
      "@id": "https://isni.org/isni/0000000122832703"
      name: "H G Wells"
      "@type": "Person"
      "ldp:inbox": "https://hgwells.com/ldn/inbox"
  systems:
    repository:
      "@id": "https://repository.org"
      "@type": "System"
      "ldp:inbox": "https://repository.org/inbox/"
    review-service:
      "@id": "https://reviewservice.org"
      "@type": "System"
      "ldp:inbox": "https://reviewservice.org/requests/inbox/"
    overlay-journal:
      "@id": "https://overlay-journal.org"
      "@type": "System"
      "ldp:inbox": "https://overlay-journal.org/requests/inbox/"
    aggregation-service:
      "@id": "https://aggregator-service.org"
      "@type": "System"
      "ldp:inbox": "https://aggregator-service.org/requests/inbox/"
  objects:
    generic_object:
      "@id": "https://reviewservice.org/review/geo/202103/0021"
      "@type": [ "Document","sorg:Review" ]
      "ietf:cite-as": "https://doi.org/10.3214/987654"
    preprint:
      "@id": "https://repository.org/preprint/201203/421/"
      "@type": "sorg:AboutPage"
      "ietf:cite-as": "https://doi.org/10.5555/12345680"
      url:
        "@id": "https://repository.org/preprint/201203/421/content.pdf"
        "@type": [ "Article","sorg:ScholarlyArticle" ]
        "media-type": "application/pdf"
    submission:
      "@id": "https://overlay-journal.org/submissions/00001/"
      "@type": "sorg:AboutPage"
      url:
        "@id": "https://overlay-journal.org/submissions/00001/files/content.pdf"
        "@type": [ "Article","sorg:ScholarlyArticle" ]
        "media-type": "application/pdf"
    review:
      "@id": "https://reviewservice.org/review/geo/202103/0021"
      "@type": [ "Document","sorg:Review"]
      "ietf:cite-as": "https://doi.org/10.3214/987654"
      "nrr:reviews":
        object:
          "@id": "https://repository.org/preprint/201203/421/"
          "ietf:cite-as": "https://doi.org/10.5555/12345680"
    "journal-review":
      "@id": "https://overlay-journal.org/reviews/000001/00001"
      "@type": [ "Document","sorg:Review" ]
      "ietf:cite-as": "https://doi.org/10.3214/987654"
      "nrr:reviews":
        object:
          "@id": "https://repository.org/preprint/201203/421/"
          "ietf:cite-as": "https://doi.org/10.5555/12345680"
    "repository-review":
      "@id": "https://repository.org/review/00001"
      "@type": [ "Document","sorg:Review" ]
      "ietf:cite-as": "https://doi.org/10.3214/000001"
      "nrr:reviews":
        object:
          "@id": "https://repository.org/preprint/201203/421/"
          "ietf:cite-as": "https://doi.org/10.5555/12345680"
    endorsement:
      "@id": "https://overlay-journal.org/articles/00001/"
      "@type": [ "Page","sorg:WebPage" ]
      "ietf:cite-as": "https://overlay-journal.org/articles/00001/"
      "nrr:endorses":
        object:
          "@id": "https://repository.org/preprint/201203/421/"
          "ietf:cite-as": "https://doi.org/10.5555/12345680"
markup:
  #  defaultMarkdownHandler: blackFriday
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: true
      table: true
      taskList: true
      typographer: false
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
#  blackFriday:
#    angledQuotes: false
#    extensions: null
#    extensionsMask: null
#    footnoteAnchorPrefix: ""
#    footnoteReturnLinkContents: ""
#    fractions: true
#    hrefTargetBlank: false
#    latexDashes: true
#    nofollowLinks: false
#    noreferrerLinks: false
#    plainIDAnchors: true
#    skipHTML: false
#    smartDashes: true
#    smartypants: true
#    smartypantsQuotesNBSP: false
#    taskLists: true